export interface modalConfig {
    modalTitle: string,
    dismissButtonLabel?: string,
    closeButtonLabel?: string,
    inputTitle?: string,
    inputDate?: Date,
    inputBody?: string,
    shouldClose?(): Promise<boolean> | boolean,
    shouldDismiss?(): Promise<boolean> | boolean,
    onClose?(): Promise<boolean> | boolean,
    onDismiss?(): Promise<boolean> | boolean,
    disableCloseButton?(): boolean,
    disableDismissButton?(): boolean,
    hideCloseButton?(): boolean,
    hideDismissButton?(): boolean,
}